In [1]:
import pandas as pd

deals = pd.read_pickle("deals_cleaned_v3.pkl")
deals

,Id,Deal Owner Name,Closing Date,Quality,Stage,Lost Reason,Page,Campaign,SLA,Content,...,Initial Amount Paid,Offer Total Amount,Contact Name,City,Level of Deutsch,Created Date,Create_to_Close_Days,Latitude,Longitude,SLA_range
0,5805028000056864695,Ben Hall,NaT,B - Medium,New Lead,NaN,/eng/test,03.07.23women,NaT,v16,...,NaN,NaN,5805028000056849495,NaN,NaN,2024-06-21,NaN,NaN,NaN,NaN
1,5805028000056859489,Ulysses Adams,NaT,B - Medium,New Lead,NaN,/at-eng,NaN,NaT,NaN,...,NaN,2000.0,5805028000056834471,NaN,NaN,2024-06-21,NaN,NaN,NaN,NaN
2,5805028000056832357,Ulysses Adams,2024-06-21,D - Non Target,Lost,Non target,/at-eng,engwien_at,0 days 00:26:43,b1-at,...,NaN,NaN,5805028000056854421,NaN,NaN,2024-06-21,0.0,NaN,NaN,Medium (15-30 min)
3,5805028000056824246,Eva Kent,2024-06-21,E - Non Qualified,Lost,Invalid number,/eng,04.07.23recentlymoved_de,0 days 01:00:04,bloggersvideo14com,...,NaN,NaN,5805028000056889351,NaN,NaN,2024-06-21,0.0,NaN,NaN,Very slow (>60 min)
4,5805028000056873292,Ben Hall,2024-06-21,D - Non Target,Lost,Non target,/eng,discovery_de,0 days 00:53:12,website,...,NaN,NaN,5805028000056876176,NaN,NaN,2024-06-21,0.0,NaN,NaN,Slow (30-60 min)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21406,5805028000050001603,Quincy Vincent,2024-05-15,E - Non Qualified,Lost,Duplicate,/eng/test,NaN,0 days 05:35:41,NaN,...,NaN,NaN,5805028000049855125,NaN,NaN,2024-05-15,0.0,NaN,NaN,Very slow (>60 min)
21407,5805028000053787195,Paula Underwood,2024-06-06,E - Non Qualified,Lost,Duplicate,/eng/test,NaN,NaT,NaN,...,NaN,NaN,5805028000053705642,NaN,NaN,2024-06-06,0.0,NaN,NaN,NaN
21408,5805028000054823001,Quincy Vincent,2024-06-12,E - Non Qualified,Lost,Duplicate,/eng,brand_search_eng_de,0 days 04:30:17,152789402780_{region_name}_668024583824,...,NaN,NaN,5805028000054480760,NaN,NaN,2024-06-12,0.0,NaN,NaN,Very slow (>60 min)
21409,5805028000056685164,Charlie Davis,2024-06-20,E - Non Qualified,Lost,Duplicate,/eng/test,NaN,0 days 00:01:46,NaN,...,NaN,NaN,5805028000056392363,NaN,NaN,2024-06-20,0.0,NaN,NaN,Very fast (â‰¤5 min)
21410,5805028000056705395,Ulysses Adams,2024-06-20,E - Non Qualified,Lost,Duplicate,/eng/test,NaN,NaT,NaN,...,NaN,NaN,5805028000056727001,NaN,NaN,2024-06-20,0.0,NaN,NaN,NaN

In [2]:
deals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21411 entries, 0 to 21410
Data columns (total 28 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Id                    21411 non-null  object
 1   Deal Owner Name       21382 non-null  object
 2   Closing Date          16685 non-null  datetime64[ns]
 3   Quality               21411 non-null  category
 4   Stage                 21411 non-null  category
 5   Lost Reason           15942 non-null  category
 6   Page                  20342 non-null  object
 7   Campaign              16006 non-null  category
 8   SLA                   15504 non-null  timedelta64[ns]
 9   Content               14101 non-null  object
 10  Term                  12387 non-null  object
 11  Source                21411 non-null  object
 12  Payment Type          496 non-null    category
 13  Product               3592 non-null   category
 14  Education Type        3299 non-null   category
 15  Created Time          21411 non-null  datetime64[ns]
 16  Course duration       3587 non-null   category
 17  Months of study       840 non-null    Int64
 18  Initial Amount Paid   3289 non-null   float64
 19  Offer Total Amount    3337 non-null   float64
 20  Contact Name          21350 non-null  object
 21  City                  2831 non-null   object
 22  Level of Deutsch      1584 non-null   category
 23  Created Date          21411 non-null  datetime64[ns]
 24  Create_to_Close_Days  16685 non-null  float64
 25  Latitude              2824 non-null   float64
 26  Longitude             2824 non-null   float64
 27  SLA_range             15504 non-null  category
dtypes: Int64(1), category(10), datetime64[ns](3), float64(5), object(8), timedelta64[ns](1)
memory usage: 3.2+ MB